"""Create user table

Revision ID: 27b4c9abdb91
Revises: 73bc6ca8265a
Create Date: 2025-11-05 21:27:10.007633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b4c9abdb91'
down_revision = '73bc6ca8265a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('role_status', sa.String(length=20), nullable=False),
    sa.Column('verification_code', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('institutional_email', sa.String(length=120), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('workplace', sa.String(length=200), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('github_profile', sa.String(length=255), nullable=True),
    sa.Column('interest_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
