"""Add SystemSetting model

Revision ID: 73bc6ca8265a
Revises: 
Create Date: 2025-11-05 15:33:37.815373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bc6ca8265a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_setting')
    # ### end Alembic commands ###
